import './globals.css'
// import { Inter } from 'next/font/google'
import { Titillium_Web } from 'next/font/google';
import { Providers } from './store/provider';

const titillium_web = Titillium_Web({
  weight: ['400', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='bg-white-900'>
      <body className={titillium_web.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
